<?php return array(
    'root' => array(
        'pretty_version' => 'dev-master',
        'version' => 'dev-master',
        'type' => 'wordpress-plugin',
        'install_path' => __DIR__ . '/../../',
        'aliases' => array(),
        'reference' => 'c321bd419e6b20ce1644db59fce20d3234bea77c',
        'name' => 'ithemes/ithemes-security-pro',
        'dev' => false,
    ),
    'versions' => array(
        'bjeavons/zxcvbn-php' => array(
            'pretty_version' => '1.4.2',
            'version' => '1.4.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../bjeavons/zxcvbn-php',
            'aliases' => array(),
            'reference' => '426f664501a0747beb8f3ee17ac30c7dd6327ffa',
            'dev_requirement' => false,
        ),
        'deliciousbrains/wp-background-processing' => array(
            'pretty_version' => '1.4.0',
            'version' => '1.4.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../deliciousbrains/wp-background-processing',
            'aliases' => array(),
            'reference' => '7ca7cc3504333db3a291bbab7f1917124fba4816',
            'dev_requirement' => false,
        ),
        'ithemes/ithemes-security-pro' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'type' => 'wordpress-plugin',
            'install_path' => __DIR__ . '/../../',
            'aliases' => array(),
            'reference' => 'c321bd419e6b20ce1644db59fce20d3234bea77c',
            'dev_requirement' => false,
        ),
        'patchstack/firewall' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'type' => 'library',
            'install_path' => __DIR__ . '/../patchstack/firewall',
            'aliases' => array(
                0 => '9999999-dev',
            ),
            'reference' => '525fe1adb710daf67c36789a076d5f8fcef01bd0',
            'dev_requirement' => false,
        ),
        'pimple/pimple' => array(
            'pretty_version' => 'v3.5.0',
            'version' => '3.5.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../pimple/pimple',
            'aliases' => array(),
            'reference' => 'a94b3a4db7fb774b3d78dad2315ddc07629e1bed',
            'dev_requirement' => false,
        ),
        'psr/container' => array(
            'pretty_version' => '2.0.1',
            'version' => '2.0.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/container',
            'aliases' => array(),
            'reference' => '2ae37329ee82f91efadc282cc2d527fd6065a5ef',
            'dev_requirement' => false,
        ),
        'stellarwp/container-contract' => array(
            'pretty_version' => '1.1.1',
            'version' => '1.1.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../stellarwp/container-contract',
            'aliases' => array(),
            'reference' => 'b2c42c76681db314e4edbb2af0a312b6c06b495e',
            'dev_requirement' => false,
        ),
        'stellarwp/telemetry' => array(
            'pretty_version' => '2.3.4',
            'version' => '2.3.4.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../stellarwp/telemetry',
            'aliases' => array(),
            'reference' => '74c7b819d574aa5fc1392f982fb32cedc18d4c6f',
            'dev_requirement' => false,
        ),
        'symfony/polyfill-mbstring' => array(
            'pretty_version' => 'v1.31.0',
            'version' => '1.31.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-mbstring',
            'aliases' => array(),
            'reference' => '85181ba99b2345b0ef10ce42ecac37612d9fd341',
            'dev_requirement' => false,
        ),
    ),
);
